### PR TITLE
Complete one import file, grab another

### PR DESCRIPTION
**Pull request by lyzidiamond**

### CODE REVIEW

**Comment by lyzidiamond** [comment]
@darrell @geografa @Caged can I get write access to this repo? I'm moving kinda quickly and I wanna make sure I don't take something someone else is working on.

**Comment by darrell** [comment]
You should have write access already. I gave it after your first pull request. Unless I screwed up.

**Comment by lyzidiamond** [comment]
@darrell I think I have access to the org, but maybe not this repo? Can you check again?

**Comment by darrell** [comment]
it says you have a pending invite. I've canceled and re-sent it.

**Comment by lyzidiamond** [comment]
Hooray! thanks @darrell!

**Pull request merged**
